"""Export design-tool data into the DevFlow Concept package format."""

from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from core.paths import PROJECT_ROOT, SANDBOX_DIR, ensure_directory_exists
WORKSPACE_DIR = SANDBOX_DIR / "workspace"


PACKAGE_NAME = "s00_cpt_v2"
ATTACHMENT_NAME = "autodesignmaker_concept.md"


def _now_iso() -> str:
    return datetime.now(timezone.utc).astimezone().replace(microsecond=0).isoformat()


def _write_json(path: Path, data: dict[str, Any] | list[Any]) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def _load_design_summary() -> dict[str, Any]:
    from core.design.data_loader import load_project_data

    data = load_project_data()
    domains = data.get("domains", [])
    if not isinstance(domains, list):
        domains = []

    domain_names: list[str] = []
    node_count = 0
    checklist_count = 0
    option_group_count = 0
    for item in domains:
        if not isinstance(item, dict):
            continue
        domain = item.get("domain", {})
        if isinstance(domain, dict):
            name = str(domain.get("name") or domain.get("id") or "").strip()
            if name:
                domain_names.append(name)
        nodes = item.get("nodes", [])
        if isinstance(nodes, list):
            node_count += len(nodes)
            for node in nodes:
                if not isinstance(node, dict):
                    continue
                checklist = node.get("checklist", [])
                if isinstance(checklist, list):
                    checklist_count += len(checklist)
                    for entry in checklist:
                        if isinstance(entry, dict) and isinstance(entry.get("optionGroups"), list):
                            option_group_count += len(entry["optionGroups"])

    meta = data.get("_meta", {})
    raw_data_source = str(meta.get("dataSource") or "") if isinstance(meta, dict) else ""
    data_source = raw_data_source
    if raw_data_source:
        try:
            source_path = Path(raw_data_source).resolve()
            data_source = str(source_path.relative_to(PROJECT_ROOT))
        except (OSError, ValueError):
            data_source = raw_data_source
    return {
        "domain_count": len(domains),
        "domain_names": domain_names,
        "node_count": node_count,
        "checklist_count": checklist_count,
        "option_group_count": option_group_count,
        "validation_errors": len(meta.get("validationErrors", [])) if isinstance(meta, dict) else 0,
        "validation_warnings": len(meta.get("validationWarnings", [])) if isinstance(meta, dict) else 0,
        "data_source": data_source,
    }


def _concept_markdown(summary: dict[str, Any]) -> str:
    domain_names = summary.get("domain_names", [])
    domain_preview = "、".join(domain_names[:8]) if isinstance(domain_names, list) else ""
    if len(domain_names) > 8:
        domain_preview += f"、and {len(domain_names) - 8} more"

    return f"""# AutoDesignMaker Concept Source

Generated by AutoDesignMaker D4 DevFlow handoff.

## Layer 1 项目愿景
Submitted / accepted
- 项目定位: AI-assisted design-to-development automation workspace
  目的：merge structured design authoring, DevFlow stage orchestration, artifact validation, and UCOS memory into one movable project.
  依赖：design_tool data domains, DevFlow orchestrator, plugin manifest
  解锁：核心循环, 技术层, 生产层
- 平台: Windows desktop application with Python CLI pipeline support
  目的：run the GUI design tool and command-line development stages from the same project root.
  依赖：Tkinter runtime, Python environment, project settings
  解锁：运行时流程
- 目标玩家: game designers, technical designers, and Unity developers
  目的：support repeated design decisions, validation, handoff, and implementation review.
  依赖：domain schema coverage, artifact reports
  解锁：内容对象, 资源类型
- 商业模式: internal production tool and reusable automation framework
  目的：prioritize correctness, traceability, migration safety, and local execution over marketing presentation.
  依赖：portable paths, deterministic exports
  解锁：影响分析

## Layer 2 核心体验
Submitted / accepted
- 核心循环: load design knowledge -> choose structured decisions -> export Concept package -> run DevFlow stages -> review artifacts
  目的：make each design-to-development handoff explicit and testable.
  依赖：data/design, source_artifacts, outputs/artifacts
  解锁：stage 00 intake, stage validation
- 压力来源: manual handoff drift, stale absolute paths, missing source packages, and unverifiable development outputs
  目的：turn migration risks into validation checks before actual Unity project mutation.
  依赖：path manager, preflight checks
  解锁：migration audit
- 奖励节奏: immediate stage summaries, validation reports, package manifests, and build artifacts
  目的：give operators fast feedback after every design or development stage.
  依赖：artifact indexes, save records
  解锁：release packaging

## Layer 3 系统图
Submitted / accepted
- system_layer: Design Engine
  目的：load domain schemas, templates, prompt frameworks, and project templates from data/design.
  依赖：{summary.get("domain_count", 0)} domains, {summary.get("node_count", 0)} nodes, {summary.get("checklist_count", 0)} checklist entries
  解锁：design stage D1-D4
- system_layer: DevFlow Orchestrator
  目的：execute stages 00-15 with preflight, artifact generation, validation, and review gates.
  依赖：orchestrator.py, stages, steps, tools
  解锁：development stage plugins
- system_layer: Artifact Layer
  目的：record stage outputs, manifests, validation reports, and review status.
  依赖：outputs/artifacts, artifact_layer
  解锁：traceability validation
- system_layer: UCOS Memory
  目的：preserve migrated procedural, episodic, and framework knowledge for repeated runs.
  依赖：ucos, memory, migrated save archives
  解锁：runtime context recall

## Layer 4 内容图
Submitted / accepted
- 内容: design domains, entity schemas, project templates, prompt frameworks, saved projects, source packages, and exported reports
  目的：keep authoring content and runtime artifacts separated while preserving legacy data.
  依赖：{domain_preview}
  解锁：package manifests and migration reports

## Layer 5 资源图
Submitted / accepted
- 资源: Python modules, JSON schemas, TOML configuration, Markdown documents, Unity project settings, and PyInstaller build output
  目的：make required runtime resources discoverable from .project_root.
  依赖：Design Engine、DevFlow Orchestrator、Artifact Layer、UCOS Memory
  解锁：portable local execution

## Layer 6 运行时图
Submitted / accepted
- 运行时: GUI launch, D-stage plugin execution, Concept package export, DevFlow stage execution, preflight checks, tests, and packaging
  目的：support both interactive design work and repeatable command-line validation.
  依赖：src/main.py, src/gui_app.py, scripts/build.py
  解锁：release verification

## Layer 7 表现层
Submitted / accepted
- 表现: Tkinter desktop shell, stage summaries, validation JSON, Markdown reviews, and command output reports
  目的：surface operational state without hiding machine-readable artifacts.
  依赖：design_tool UI, artifact reports
  解锁：manual review and debugging

## Layer 8 技术层
Submitted / accepted
- 技术: root-marker path resolution, TOML/JSON config loading, manifest-based plugins, legacy adapters, pytest checks, and PyInstaller packaging
  目的：make the merged project relocatable and independently verifiable.
  依赖：src/core, src/plugins, scripts
  解锁：packaged executable

## Layer 9 生产层
Submitted / accepted
- 生产: migrate legacy assets, validate structure, run smoke stages, export Concept package, preflight Unity settings, run tests, and build executable
  目的：turn the original merge plan into a repeatable delivery workflow.
  依赖：migration report, stage reports, test results
  解锁：handoff-ready project

## Layer 10 影响分析
Submitted / accepted
- 影响: path independence, source package compatibility, legacy save preservation, stage contract stability, and Unity mutation boundary
  目的：make the risky parts of the merge visible before full development execution.
  依赖：hardcoded-path scan, preflight-only run, formal stage 00 intake
  解锁：controlled downstream stage execution
"""


def _package_payload(package_dir: Path, attachment_rel: str, summary: dict[str, Any]) -> dict[str, Any]:
    created_at = _now_iso()
    return {
        "created_at": created_at,
        "manifest": {
            "schema_version": 1,
            "project": "AutoDesignMaker",
            "project_id": "autodesignmaker",
            "package_id": "source:Concept",
            "package_type": "Concept",
            "package_type_id": "concept",
            "source_id": "Concept",
            "source_ids": ["Concept"],
            "stage": 0,
            "stage_slug": "idea_intake",
            "stage_title": "Initial Idea Intake",
            "version": 2,
            "generated_by": "src.plugins.adapters.design_export_adapter",
            "design_summary": summary,
        },
        "submission": {
            "schema_version": 1,
            "project": "AutoDesignMaker",
            "project_id": "autodesignmaker",
            "step": 0,
            "slug": "idea_intake",
            "title": "Initial Idea Intake",
            "created_at": created_at,
            "approved": True,
            "notes": "AutoDesignMaker D4 exported a parseable Layer document for DevFlow Stage 00.",
            "decisions": {
                "Design data loaded without validation errors": summary.get("validation_errors", 0) == 0,
                "Concept package is parseable by Stage 00": True,
                "Package may be used as the current development source": True,
            },
            "attachments": [attachment_rel],
            "primary_attachment": attachment_rel,
            "package_type": "Concept",
            "source_id": "Concept",
            "source_ids": ["Concept"],
        },
    }


def _write_package(package_dir: Path, summary: dict[str, Any]) -> None:
    attachments_dir = ensure_directory_exists(package_dir / "attachments")
    attachment_rel = f"attachments/{ATTACHMENT_NAME}"
    attachment_path = attachments_dir / ATTACHMENT_NAME
    markdown = _concept_markdown(summary)
    attachment_path.write_text(markdown, encoding="utf-8")

    payload = _package_payload(package_dir, attachment_rel, summary)
    manifest = payload["manifest"]
    submission = payload["submission"]
    _write_json(package_dir / "package_manifest.json", manifest)
    _write_json(package_dir / "operator_submission.json", submission)
    _write_json(package_dir / "human_approval.json", {
        "schema_version": 1,
        "approved": True,
        "approved_at": payload["created_at"],
        "reviewer": "AutoDesignMaker D4",
        "source_attachment": attachment_rel,
    })
    _write_json(package_dir / "selected_play_prototype.json", {
        "schema_version": 1,
        "id": "ADM-CONCEPT-001",
        "selected": True,
        "description": "AutoDesignMaker merged design-to-development workflow.",
        "source_attachment": attachment_rel,
    })
    _write_json(package_dir / "prototype_candidates.json", {
        "schema_version": 1,
        "selected_id": "ADM-CONCEPT-001",
        "candidates": [
            {
                "id": "ADM-CONCEPT-001",
                "title": "AutoDesignMaker design-to-development workflow",
                "selected": True,
            }
        ],
    })
    _write_json(package_dir / "creative_points.json", {
        "schema_version": 1,
        "points": [
            "Portable project-root path resolution",
            "Manifest-driven D-stage and DevFlow-stage plugin bridge",
            "Deterministic Concept package export for Stage 00",
        ],
    })
    _write_json(package_dir / "open_questions.json", {
        "schema_version": 1,
        "questions": [
            {
                "id": "ADM-Q001",
                "question": "Whether to run Stage 10 against the configured external Unity project.",
                "status": "operator_decision_required",
            }
        ],
    })
    _write_json(package_dir / "selection_history.json", {
        "schema_version": 1,
        "entries": [
            {
                "selected_id": "ADM-CONCEPT-001",
                "selected_at": payload["created_at"],
                "reason": "Generated from migrated design data and merge-plan execution state.",
            }
        ],
    })
    (package_dir / "selected_play_prototype.md").write_text(
        "# Selected Prototype\n\nAutoDesignMaker merged design-to-development workflow.\n",
        encoding="utf-8",
    )
    (package_dir / "human_review.md").write_text(
        "# Human Review\n\nApproved for DevFlow Stage 00 intake by deterministic D4 export.\n",
        encoding="utf-8",
    )
    (package_dir / "stage_input.md").write_text(markdown, encoding="utf-8")


def export_concept_package(
    *,
    target_dir: Path | None = None,
    mirror_workspace: bool = True,
) -> dict[str, Any]:
    """Create a Stage 00 Concept package from current design-tool data.

    The legacy DevFlow runtime reads root-level ``source_artifacts``. A mirror is
    also written under ``workspace/source_artifacts`` for the new project layout.
    """

    root_source_dir = PROJECT_ROOT / "source_artifacts"
    package_dir = target_dir or (root_source_dir / PACKAGE_NAME)
    package_dir = ensure_directory_exists(package_dir)
    summary = _load_design_summary()
    _write_package(package_dir, summary)

    mirrors: list[str] = []
    if mirror_workspace:
        workspace_package_dir = WORKSPACE_DIR / "source_artifacts" / PACKAGE_NAME
        if workspace_package_dir.resolve() != package_dir.resolve():
            ensure_directory_exists(workspace_package_dir.parent)
            if workspace_package_dir.exists():
                shutil.rmtree(workspace_package_dir)
            shutil.copytree(package_dir, workspace_package_dir)
            mirrors.append(str(workspace_package_dir))

    return {
        "package_dir": str(package_dir),
        "attachment": str(package_dir / "attachments" / ATTACHMENT_NAME),
        "mirrors": mirrors,
        "design_summary": summary,
    }


__all__ = ["ATTACHMENT_NAME", "PACKAGE_NAME", "export_concept_package"]
