#!/usr/bin/env python3
"""兼容旧流水线步骤模块 — 同步导出所有 15 步常量。"""

from tools.pipeline_registry import (
    NON_RUNNABLE_STATUSES,
    PIPELINE_STEPS,
    STEP_ART_PLAN,
    STEP_ART_PRODUCTION,
    STEP_ART_REQUIREMENTS,
    STEP_ART_REQUIREMENTS_REVIEW,
    STEP_ASSET_ALIGNMENT,
    STEP_BUILD,
    STEP_BY_NUMBER,
    STEP_DELTA_PATCH,
    STEP_MIGRATION_AUDIT,
    STEP_DEMO,
    STEP_DESIGN_REVIEW,
    STEP_DESIGN_TO_PLAN,
    STEP_DEV_EXECUTION,
    STEP_IDEA_INTAKE,
    STEP_INTEGRATION_VALIDATION,
    STEP_PROGRAM_REQUIREMENTS,
    STEP_PROGRAM_REQUIREMENTS_REVIEW,
    STEP_NAMES,
    PipelineStep,
    completed_dependencies,
    dependencies_satisfied,
    get_step,
    get_step_name,
    iter_steps,
    latest_step_status,
    max_step_number,
    missing_dependencies,
    runnable_steps,
)

__all__ = [
    "NON_RUNNABLE_STATUSES",
    "PIPELINE_STEPS",
    "STEP_ART_PLAN",
    "STEP_ART_PRODUCTION",
    "STEP_ART_REQUIREMENTS",
    "STEP_ART_REQUIREMENTS_REVIEW",
    "STEP_ASSET_ALIGNMENT",
    "STEP_BUILD",
    "STEP_BY_NUMBER",
    "STEP_DELTA_PATCH",
    "STEP_MIGRATION_AUDIT",
    "STEP_DEMO",
    "STEP_DESIGN_REVIEW",
    "STEP_DESIGN_TO_PLAN",
    "STEP_DEV_EXECUTION",
    "STEP_IDEA_INTAKE",
    "STEP_INTEGRATION_VALIDATION",
    "STEP_NAMES",
    "STEP_PROGRAM_REQUIREMENTS",
    "STEP_PROGRAM_REQUIREMENTS_REVIEW",
    "PipelineStep",
    "completed_dependencies",
    "dependencies_satisfied",
    "get_step",
    "get_step_name",
    "iter_steps",
    "latest_step_status",
    "max_step_number",
    "missing_dependencies",
    "runnable_steps",
]
